artifact_location: file:///c:/Users/admin/OneDrive/Desktop/pharma%20project-6/Pharma-project-6/mlruns/0
creation_time: 1712599530837
experiment_id: '0'
last_update_time: 1712599530837
lifecycle_stage: active
name: Default
